import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '../styles/Home.module.css'

const DynamicBasicDocument = dynamic(() => { return import('./_basicDoc') }, { ssr: false })


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <DynamicBasicDocument />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
